### ISSUE TITLE
Test memory boundaries for opcode execution

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-vm#38]
We are to use words as pairs of encoded instructions.

However, jump instructions are half-word. And we also might interrupt a program (e.g. debug) in a half-word

This means that incrementing by word might lead to invalid memory access in case the code is in the memory boundary.

We need to have a test case covering that - and, if applicable, fix the code so no panic occur.

**Comment by xgreenx** [comment]
How do you think is this issue actual for us with our current codebase?

**Comment by Dentosal** [comment]
> How do you think is this issue actual for us with our current codebase?

I'm fairly certain that this isn't an issue anymore. However, it would still be simple to refactor the instruction fetch code so that we could be certain. The current version is somewhat convoluted, as it's supposedly optimized by loading two opcodes at once. I presume that since we don't guarantee instruction alignment anyway, a simpler obviously-correct apporach would have the same performance.
