### ISSUE TITLE
Large contracts take a very long time to merkleize

### ISSUE THREAD

**Issue by Voxelot** [FuelLabs/fuel-vm#385]
While we aim to support contract sizes of up to 16mb, this takes an excess of 20s+ to deploy onto a node due to the contract root calculation. The contract root exists to provide a mechanism to prove that the code being executed is actually part of the contract. However, the root is computed by chunking every opcode into a BMT leaf, which ends up causing millions of sha256 hash operations for a 16mb contract.

Our options are:
- Reduce max contract size to a level that is reasonable for merklizing
- Use larger chunks for the contract root (e.g. 32+ bytes / 4+ opcodes per leaf, maybe 1KiB chunks would be ok for ethereum fraud proofs?)
- Parallelize computing of contract roots (e.g. rayon)
- Investigate a more efficient way of computing the root when all leaves are present (e.g. regular merkle tree instead of BMT since it's not going to be appended to)
- Verify contract root on checked txs, and avoid re-verifying it during the `deploy` executor in fuel-vm (still potentially impacts our consensus/sync time)

**Comment by Voxelot** [comment]
Some initial benchmarking shows that using grouping ops into larger chunks when merkleizing makes a fairly substantial impact on performance:

When merklizing 16kib of contract code
```
word sized (8) chunks          time:   [1.1178 s 1.1211 s 1.1245 s]
quad sized (32) chunks         time:   [234.35 ms 235.35 ms 236.45 ms]
1 kib sized (1024) chunks      time:   [11.627 ms 11.633 ms 11.639 ms]
page sized (4096) chunks       time:   [8.5189 ms 8.5468 ms 8.5737 ms]
```

**Comment by ControlCplusControlV** [comment]
Is there a reason to use `rayon`? AFAIK you could spawn a tokio task for each contract root, and since they are very efficient and have minimal overhead being slightly heavier than a [goroutine](https://www.reddit.com/r/rust/comments/lg0a7b/benchmarking_tokio_tasks_and_goroutines/)

**Comment by mitchmindtree** [comment]
Maybe a bit late in the game for this, but is it maybe worth seeing if it's feasible to swap out sha256 for blake3? https://crates.io/crates/blake3.

They seem to boast an order of magnitude improvement in performance in single-threaded environments, and it looks like it's also parallel-friendly so could potentially get even greater wins.

I'm not savvy enough to know how involved such a change would be, or if there is some other reason (safety or otherwise) we prefer sha256? Just thought I'd share as I came across it while investigating IPFS implementations for the forc pkg registry ([this](https://www.youtube.com/watch?v=nk4nefmguZk) was a good watch).

Curiously, the hashing implementation itself **is** a binary merkle tree (which is what makes it parallel-friendly). I wonder if we could just hash the bytecode entirely with blake3, and then use *that* merkle tree to resolve fraud disputes? blake3 appears to use a fixed chunk size of 1kB, so you could potentially use the offset to get an idea of which group of opcodes could have resulted in the dispute? Totally spitballing here :sweat_smile:

**Comment by SilentCicero** [comment]
Blake3 is going to be difficult or potentially not possible to fraud prove on many EVM systems, which is our typical L1 target right now.

Blake3 is also a little suspect as a secure hashing function, and I don't believe carries the same scrutiny and security that sha256 or sha3 has, although that is not my area of expertise. I believe from what I read it arguably falls under 128-bits of security, which is not necessarily acceptable.

I think reducing contract size and increasing leaf size gets us pretty close right now, should drop most contracts to between 7-30ms based upon preliminary estimates (which for me is still *not ideal* but something we can live with for now).

FWIW there is an implementation of blake3 we could use under the hood in Solidity (which is not audited and has no benchmarks posted), but it wouldn't be very clean:
https://github.com/mel-project/blake3-sol and no idea what the benchmarks are for this, or if it could appropriately hash a large chunk of data on Ethereum for us.

**Comment by Voxelot** [comment]
fixed by: https://github.com/FuelLabs/fuel-vm/issues/434
