### ISSUE TITLE
Sparse Merkel tree leafs/nodes may override other leafs/nodes

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#472]
Sparse Merkel tree leafs/nodes may override other leafs/nodes because we use the same storage for the nodes and leafs.
Unit test [here](https://github.com/FuelLabs/fuel-vm/pull/469) shows the problem.

Thread from the slack:
@xgreenx : 

> Actually, regarding [this comment](https://github.com/FuelLabs/fuel-vm/pull/469#issuecomment-1574526210). In the [ink!](https://use.ink/) they decided to hash each storage key to preventing data structure manipulation(like Merkle Tree). Because the code is public and you know how it works inside, you can push the data to the contract and manipulate the internal state of the data structure. It may make them non-optimal and operations will take more time than expected.
>
> Maybe we want to think about it too. Because without it we have the bug like in [this](https://github.com/FuelLabs/fuel-vm/pull/469) PR=)

@bvrooman : 
> It sounds reasonable to hash storage keys. In general, it might be a good idea to avoid putting user input directly into the storage's primary keys like that.
>
> It sounds like we have two options:
> 1. Hash direct user input used as primary keys
> 1. Use separate storages for leaves and nodes2. 
>
> If option 1 is sufficient, that would be the quickest win. Option 2 is more involved, and may introduce other performance issues, but it allows us to avoid the extra hash and reduce the impact of collisions.

@xgreenx : 
> I think it is always good to have separate storage for leaves. In this case, we don’t need to worry about SMT, and because each storage has fewer entries, DB will work faster.
I think we definitely need to consider doing hashing from a security perspective. The problem is that we cannot iterate over the storage with this approach. But maybe we can check how substrate solved this problem(because I know they still can iterate over it even with hashing of the primary keys)

**Comment by Voxelot** [comment]
I agree that some separate storage table or a different key structure for leaves is probably the best call (Ie prefix add a sentinel bit to the bytes32). This is because any key from 0..2^255 is a valid leaf key, and so even with hashing the key there is is nothing explicitly preventing a collision as the tree grows.

**Comment by bvrooman** [comment]
The reason I say that using two storage tables may introduce a performance issue is that we will have to check both storage tables when accessing a child node. This is because nodes essentially have "pointers" to child nodes: they store the left 32-byte address and the right 32-byte address. This means:
- When looking up the child, we have to first check Node Storage. If it's not in Node Storage, we then check Leaf Storage.  In this scenario, we incur a lookup miss.
- If Node Storage and Leaf Storage contain the same key, we run into collision issues still. For example, if the child is in Leaf Storage, but I first check Node Storage, I will return the node from Node Storage, when I wanted the one in Leaf Storage. This means we are still suffering from collision issues. 
- These are all still true if you switch the order to check Leaf Storage first and then Node Storage.
