### ISSUE TITLE
Limit `$pc` to always stay within `$ssp`..`$sp`

### ISSUE THREAD

**Issue by xgreenx** [FuelLabs/fuel-vm#616]
It should resolve the https://github.com/FuelLabs/fuel-vm/issues/564

**Comment by dmihal** [comment]
How does this affect upgradability or other use cases where it's desirable to execute arbitrary code?

**Comment by Dentosal** [comment]
This doesn't work at all. Firstly, VM is initialized `$ssp=$sp` and `$pc < $ssp`. Secondly, you can still write to stack.

**Comment by xgreenx** [comment]
It seems the rule like `$pc < $ssp` should work?=D

**Comment by Dentosal** [comment]
Likely. I'm trying to think it through.

**Comment by Dentosal** [comment]
Feels like `$is <= $pc < $ssp` would be the bounds we want

**Comment by Voxelot** [comment]
This makes more sense and works great for contract calls. My only concern is for script execution, since the script bytecode isn't the only data in-between `$is..$ssp`. Granted, this isn't really much of a security risk, but it could lead to weird things like the vm trying to parse random transaction bits as instructions and cause unexpected behavior.
