### ISSUE TITLE
Use `max_fee` policy to charge user

### ISSUE THREAD

**Issue by MitchTurner** [FuelLabs/fuel-vm#665]

**Comment by MitchTurner** [comment]
This was on the Miro board, but I'm not sure what it means :P

**Comment by xgreenx** [comment]
The current codebase converts `max_gas` into `max_fee` and deducts this amount from available balances. 
<img width="1275" alt="image" src="https://github.com/FuelLabs/fuel-vm/assets/18346821/958d98e4-1bcf-432f-97f5-d375b9125e19">

It was okay to do because `gas_price` was statically defined by the transaction itself. But in a new module, since the base gas price is dynamic, the `max_fee` based on the `max_gas` is dynamic too. Instead of using this dynamic value, we need to use `max_fee` defined by the user in the policies if it is available.

**Comment by MitchTurner** [comment]
Are we keeping `script_gas_limit`? I'm still confused about the relationship between gas limit and `max_fee`.

**Comment by Voxelot** [comment]
yes we need to keep script_gas_limit as a way for users to budget how much of their fee goes into script execution vs witness data etc
